### ISSUE TITLE
Ubuntu Docker collection

### ISSUE THREAD

**Issue by BSDVTUX** [FSecureLABS/LinuxCatScale#10]
On a known Ubuntu system with  Docker running I was receiving no collection for the Docker containers.  I noticed under the execution section for Ubuntu, at Line 778 in Cat-Scale.sh,  the following 2 lines were missing:

 			echo " - Docker and Virtual Machine info..."
			get_docker_info

Addition of those lines resulted in a collection.

**Comment by 56616c6f72** [comment]
Fixed this issue. Sorry it took me so long. I saw it and forgot to address it. For future please feel free to submit a PR.
