### ISSUE TITLE
Incomplete routing information ?

### ISSUE THREAD

**Issue by Garamotte** [FSecureLABS/LinuxCatScale#11]
Hello,

On Linux, your script only collects the main routing table:
https://github.com/WithSecureLabs/LinuxCatScale/blob/76302aa1cf8a3df2c0250cdcd866def744fb3ccd/Cat-Scale.sh#L293-L294

I would suggest to call `ip rule` and `ip --details route show table all` instead of only `ip route` to get more information.

**Comment by 56616c6f72** [comment]
Nice thanks for the tip. I updated it to `ip --details route show table all`

I didn't add `ip rule` as it seem the output of `ip --details route show table all` covers the information provided there.
