### ISSUE TITLE
Bad link to description of what is collected

### ISSUE THREAD

**Issue by tko** [FSecureLABS/LinuxCatScale#12]
> This script will produce output and archive. Currently most up to date what it collects is covered in the blog post here: https://labs.f-secure.com/tools/cat-scale-linux-incident-response-collection/

The link leads to https://blog.f-secure.com/category/threats-research/ listing page instead of blog post.

**Comment by 56616c6f72** [comment]
Hi Tommi! 

Hope you are having a good day! Thank you for raising this. It was working for sometime after f-secure, withsecure demerger but it looks like the websites are not completely seperate now. 

I updated the link on the read me. The correct one is https://labs.withsecure.com/tools/cat-scale-linux-incident-response-collection

Thanks!
