### ISSUE TITLE
Error when gvfs is not available

### ISSUE THREAD

**Issue by Jil** [FSecureLABS/LinuxCatScale#5]
In a recent case, I used the script on Suse Linux Enterprise, and the lsof excluding gvfs caused an error. If I remember correctly, it didn't like the fact that excluded path didn't exist.

https://github.com/FSecureLABS/LinuxCatScale/blob/0dc50570b295fe424aa81de89b97703df0525415/Cat-Scale.sh#L231

I worked it around by removing the `-e` parameter. I wonder whether it should be kept, in which case an additional if clause could be added for better compatibility; or if it could just get stripped.

**Comment by 56616c6f72** [comment]
This is more a future request for Cat-Scale to support SUSE. 

So right now we have not tested Cat-Scale against SUSE. Anytime we ran Cat-Scale against a non-tested OS it does a best effort collection so some data will be missing. 

If you have a SUSE vm in place. I can guide/help you test and develop official support for it.  We would look to create dedicated functions for SUSE and reuse what's in place where we can.
